spring.application.name=reviewms
server.port=8083

#H2 Database
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true

#PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/reviewms
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Config Server
spring.config.import=optional:configserver:http://localhost:8084